### PR TITLE
[DEV APPROVED]change dynamically rendered route to path

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
* changed from URL to path
  * the URL contains the full resource locator. This makes a request from an unsecured source for a secure resource.

### CODE REVIEW

**Comment by jongilbraith** [comment]
👍

**Comment by rnalexander** [comment]
:+1: :shipit:

**Comment by Tr4pSt3R** [comment]
Thanks @jongilbraith && @rnalexander

**Comment by tomas-stefano** [comment]
:+1:

**Pull request merged**
