### PR TITLE
Allow for unusual characters within anchor links

### PR DESCRIPTION
**Pull request by jonalport**

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1:

**Comment by asmega** [comment]
this will have to marry up with the ruby implementation for auto ids otherwise we'll get dead links

**Comment by asmega** [comment]
which can be found here https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/base.rb#L232

**Comment by jonalport** [comment]
@asmega: This is a valid point. The implementations are the same, except that the ruby allows for multiple consecutive hyphens, which is suboptimal IMHO.

Example string: "Hello , there"

In ruby: "hello--there"

In JS: "hello-there"

Can we edit the ruby or not so much?

**Comment by asmega** [comment]
I don't fancy patching as it's a third party lib so will probably leave as is.

**Comment by jonalport** [comment]
Thought as much :)

**Comment by benbarnett** [comment]
post-25179-you-can-do-it-gif-waterboy-img-jc2v

**Comment by jonalport** [comment]
Haha! Ok, I've got this.

**Comment by jonalport** [comment]
@asmega: it is done

**Comment by asmega** [comment]
:+1:

**Pull request merged**
