### PR TITLE
[DEV APPROVED]Bump mastalk 0.5.5 to 0.5.6

### PR DESCRIPTION
**Pull request by johnplayer1982**
Bump mastalk version to 0.5.6, Updated mastalk gem pushed to rubygems,
relates to https://github.com/moneyadviceservice/mastalk/pull/9

### CODE REVIEW

**Comment by asmega** [comment]
you want to add and push the commit of `0.5.6` into the `mastalk` repository so its in version control

**Comment by johnplayer1982** [comment]
mastalk repo updated, thanks @asmega !

**Comment by asmega** [comment]
:+1:

**Comment by nmiddleweek** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Pull request merged**
