### PR TITLE
Further fix for Dialog rendering on InsertManager

### PR DESCRIPTION
**Pull request by ourmaninamsterdam**
Strangely, my previous fix worked locally, but not on QA. This one *should* do it :four_leaf_clover: 

Previous [PR](https://github.com/moneyadviceservice/cms/pull/164) with issue explained.

@moneyadviceservice/frontend

### CODE REVIEW

**Comment by benbarnett** [comment]
:rocket:

**Comment by Guntrisoft** [comment]
:+1:

**Comment by ourmaninamsterdam** [comment]
Cheers for the :+1: . On QA, my previous fix now seems to be working despite being there and not working before. :neutral_face: So, I'm going to leave this open for a bit in case it decides to die again.

**Comment by ourmaninamsterdam** [comment]
Merging this as the previous fix no longer seems to be working. Hmmm. Anyway, :four_leaf_clover: this one works.

**Pull request merged**
