### PR TITLE
[DEV APPROVED] Adding Vimeo embed snippet

### PR DESCRIPTION
**Pull request by johnplayer1982**
Enabling an editor to embed Vimeo videos, Relates to https://github.com/moneyadviceservice/mastalk/pull/12

### CODE REVIEW

**Comment by asmega** [comment]
:+1:

**Comment by johnplayer1982** [comment]
Sorry @asmega I've added a new change, bumped mastalk version, 0.5.7 pushed to rubygems

**Comment by asmega** [comment]
:+1:

**Comment by nmiddleweek** [comment]
:+1:

**Pull request merged**
