### PR TITLE
Hippo import interface

### PR DESCRIPTION
**Pull request by tomas-stefano**
Create this PR due to the actual migration steps that need to be done to migrate to hippo.

So I make a simple (very ugly actually) UI that is possible to import pages from hippo to contento. 

This will be removed soon, after all pages are migrated.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Waiting for approval. Don't forget to see the description of PR. 
waiting-for-pr-approval

**Comment by dougdroper** [comment]
:+1:

**Comment by alexwllms** [comment]
No code feedback at all. But brilliant use of GIF @tomas-stefano

**Comment by tomas-stefano** [comment]
@alexwllms hehehe. I make the comment just to show the gif XD. Somebody could give one more thumbs up?

**Comment by alexwllms** [comment]
:+1:

**Pull request merged**
