### PR TITLE
[DEV APPROVED] Rubocop fixes

### PR DESCRIPTION
**Pull request by KateWilkinson**
Running rubocop, there were 157 issues detected.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Great! :+1: 
I use this scrippt as pre-commit hook in order to avoid rubocop erors. Maybe everybody could use (or improve): https://gist.github.com/tomas-stefano/fa46e26b5778ec1f7030

**Comment by KateWilkinson** [comment]
@tomas-stefano thanks for the thumb! We've just had to add an additional refactor to keep code climate happy, as it's now able to spot a duplication it wasn't previously able to detect.

**Comment by tomas-stefano** [comment]
LG :+1:

**Comment by cazrin** [comment]
:+1: if the Rubocop God is happy.

**Pull request merged**
