### PR TITLE
Adding a one-shot rake task to set published_at date on pages

### PR DESCRIPTION
**Pull request by urfolomeus**

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:+1: lgtm. 

well-explained

**Comment by urfolomeus** [comment]
@tomas-stefano implemented your suggestion :point_up:

**Comment by tomas-stefano** [comment]
Nice. Can you squash both commits?

**Comment by urfolomeus** [comment]
Will do.

**Comment by urfolomeus** [comment]
@tomas-stefano done

**Comment by tomas-stefano** [comment]
:+1: :shipit:

**Pull request merged**
