### PR TITLE
Improvements to the post scheduling interface

### PR DESCRIPTION
**Pull request by jongilbraith**
Most of the changes are in [another PR](https://github.com/moneyadviceservice/comfortable-mexican-sofa/pull/20) on the comfy gem, for which a few tweaks were needed in this codebase.  Will rebase the Gemfile changes once that PR's been merged.

Other than that, there's a small change to make the schedule dialogue prepopulates the time/date if there's one already set.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
Hey @jongilbraith could you, per chance, use http://recordit.co to show the changes to the scheduling interface.

**Comment by jongilbraith** [comment]
@Tr4pSt3R

Demo

**Comment by Tr4pSt3R** [comment]
Nice one @jongilbraith, makes it easier to review. 
:+1: :+1:

**Comment by tomas-stefano** [comment]
Nice! :+1: :+1:

**Comment by jongilbraith** [comment]
Have found a flaw in this implementation, so setting it WIP while I decide on a solution.

**Comment by jongilbraith** [comment]
Flaw has been addressed. Full explanation in [the other PR](https://github.com/moneyadviceservice/comfortable-mexican-sofa/pull/20). Simply put though, the functionality I added to unschedule posts has now been removed (it needed more work and wasn't part of the originally reported issue).

Have recorded another capture, this time with one of the previous behaviour.

Before

Before...

After

After...

**Comment by tomas-stefano** [comment]
:+1:

**Comment by habitullence** [comment]
:+1:

**Pull request merged**
