### PR TITLE
Home page editing

### PR DESCRIPTION
**Pull request by jonalport**
This adds a new "home page" content type to the CMS, along with a bunch of fields to edit several components of the MAS home page.

There should be a new home page content item published (layout = 'home_page') having slug = 'the-money-advice-service'. The required layout fields are detailed in the template '_home_page.html.erb'.

The corresponding frontend work is detailed here:
https://github.com/moneyadviceservice/frontend/pull/1257

home page

### CODE REVIEW

**Comment by asmega** [comment]
I think this is now in a state to be reviewed

**Comment by Tr4pSt3R** [comment]
@asmega will you be taking charge of any proposed changes in Jon's absence please/?

**Comment by Tr4pSt3R** [comment]
@asmega oh yes, ignore my earlier question. I see that you are already actively on this story.

**Comment by tomas-stefano** [comment]
LGTM :+1: :+1:

**Comment by asmega** [comment]
ok another re-review

**Comment by tomas-stefano** [comment]
:+1:

**Comment by darokel** [comment]
:+1: awesome

**Pull request merged**
