### PR TITLE
Make tests of file listings in admin page not fail.

### PR DESCRIPTION
**Pull request by misaka**

### CODE REVIEW

**Comment by asmega** [comment]
:+1:

**Comment by misaka** [comment]
@asmega I've changed this so that it sorts the list of files in the expectation instead of when it generates the list of files. It seems to make sense to move the sorting closer to the expectation.

**Comment by Tr4pSt3R** [comment]
I wonder if it would be better if ```filenames_of(type: type).sort``` was spelt out as to filetypes are being expected?

**Comment by misaka** [comment]
@Tr4pSt3R I think I've just made that change, actually. Could you refresh and double-check that that's what you meant?

**Comment by Tr4pSt3R** [comment]
I feel it will be clearer to spell out the filenames of a definite type. i.e.

```expect(shown_filenames).to eq(filenames_of(type: type).sort)``` should be
```expect(shown_filenames).to eq[‘file_a’, ‘file_b]```
the eq part, I feel should always be explicit

**Comment by Tr4pSt3R** [comment]
:+1: good to go though

**Comment by asmega** [comment]
:+1:

**Pull request merged**
