### PR TITLE
Update to Dough 5.1.0 - restructure SCSS and @imports

### PR DESCRIPTION
**Pull request by ourmaninamsterdam**
Bumps Dough to 5.1.0. This introduced a new structure for SCSS and this PR brings the CMS inline with this.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
LGTM :+1:

**Comment by neoeno** [comment]
I'm getting `File to import not found or unreadable: yeast/assets/lib/all.` on the cucumbers when I run `./test.sh`. Not sure if it's my local environment, going to clear and retry.

**Comment by ourmaninamsterdam** [comment]
Have you done a `bowndler install`?

**Comment by neoeno** [comment]
Yep — `test.sh` does that itself also.

Seeing this consistently on a fresh clone with a fresh gemset. 

Output of `test.sh` here: https://gist.github.com/neoeno/bffabab8b2297bbd1d56 . 

`bower.json` here: https://gist.github.com/neoeno/949a1a060745238b5303

**Comment by ourmaninamsterdam** [comment]
After chatting with @neoeno offline we determined it was missing the [yeast](git://github.com/moneyadviceservice/yeast.git#master) declaration in `bower.json.erb`. This has now been included.

**Comment by neoeno** [comment]
:+1:

**Comment by dougdroper** [comment]
:+1:

**Pull request merged**
