### PR TITLE
[DEV APPROVED] Added `ExternalLink` post processor for screen readers 

### PR DESCRIPTION
**Pull request by jriga**
**Feature**
Append visually hidden tag to improve accessibility for screen readers.
[Card 7669](https://moneyadviceservice.tpondemand.com/entity/7669)

Dev: @tomas-stefano @jriga

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by jongilbraith** [comment]
Brilliant, was hoping there might be a mechanism like this available to do this. 👍

**Comment by slaywell** [comment]
Can we translate the hidden text into Welsh when on a Welsh page?

**Comment by slaywell** [comment]
Also 'open in a tab' might not be the best description - how about '(opens in new window)'?

**Comment by jriga** [comment]
@slaywell I'm looking into the welsh version. 
I don't mind the changing the text, I'll have a chat with @edmundward about that.

**Comment by jriga** [comment]
👀 @tomas-stefano @jongilbraith

**Comment by slaywell** [comment]
It's a 👍 from me, thanks @jriga

**Comment by jongilbraith** [comment]
LGTM 👍

**Comment by tomas-stefano** [comment]
👍

**Pull request merged**
