### PR TITLE
[WIP] - add csrf protection

### PR DESCRIPTION
**Pull request by asmega**
this seemed to be accidentally removed a while back

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1:

**Comment by munckymagik** [comment]
22 days ago? Is this alive? :+1:

**Comment by tomas-stefano** [comment]
Is this good to go?

**Comment by asmega** [comment]
sorry it needs to be regression tested

Thanks
Phil

sent from my phone

On 3 Feb 2016, at 13:57, tomas-stefano <notifications@github.com> wrote:

Is this good to go?

—
Reply to this email directly or view it on GitHub
<https://github.com/moneyadviceservice/cms/pull/274#issuecomment-179248220>.

**Pull request closed without merging**
